"""
Compliance guardrail — SEBI/RBI/IRDAI/IT Act rules.
Always runs last. Non-bypassable. Logs every interaction.

Regulatory basis:
- SEBI (Investment Advisers) Regulations, 2013
- RBI guidelines on financial literacy
- IRDAI insurance advisory norms
- Income Tax Act, 1961
"""
from __future__ import annotations
import json
import re
import uuid
from datetime import datetime
from pathlib import Path

# ── Mandatory SEBI disclaimer ─────────────────────────────────────────────────
DISCLAIMER = (
    "\n\n─────────────────────────────────────────\n"
    "📋 Regulatory Disclaimer\n"
    "─────────────────────────────────────────\n"
    "This analysis is generated by an AI system for educational and "
    "informational purposes only. It does NOT constitute investment advice, "
    "financial planning advice, or tax advice as defined under:\n"
    "• SEBI (Investment Advisers) Regulations, 2013\n"
    "• Income Tax Act, 1961\n"
    "• IRDAI insurance advisory regulations\n\n"
    "All tax figures are based on Finance Act 2024 (FY 2024-25) and are "
    "indicative. Actual liability may vary based on your complete income details.\n\n"
    "Before acting on any suggestion, please consult:\n"
    "• A SEBI-Registered Investment Adviser (RIA) for investment decisions\n"
    "• A Chartered Accountant (CA) for tax filing\n"
    "• A licensed insurance advisor for insurance products\n\n"
    "SEBI Investor Helpline: 1800-266-7575 | sebi.gov.in/investors\n"
    "Income Tax Helpline: 1800-103-0025 | incometaxindia.gov.in"
)

# ── Patterns that cross into unlicensed advice territory ─────────────────────
SOFTENING_RULES = [
    (r"\byou (must|should) (buy|invest|purchase)\b",    r"you may consider \2ing"),
    (r"\bguaranteed (returns?|gains?|profit)\b",         "historical returns (not guaranteed)"),
    (r"\bwill definitely\b",                             "may potentially"),
    (r"\b100% (safe|secure|risk.?free)\b",               "relatively lower risk"),
    (r"\bbest (fund|stock|scheme)\b",                    "a suitable option"),
    (r"\bI recommend (buying|investing in|purchasing)\b", r"you may consider \1"),
]

AUDIT_LOG_PATH = Path("audit_log.jsonl")


def apply_guardrail(response: str, user_id: str = "anonymous", scenario: str = "") -> str:
    """Sanitize response language and append mandatory disclaimer."""
    sanitized = response
    for pattern, replacement in SOFTENING_RULES:
        sanitized = re.sub(pattern, replacement, sanitized, flags=re.IGNORECASE)
    sanitized += DISCLAIMER
    _log_interaction(user_id, scenario, len(sanitized))
    return sanitized


def _log_interaction(user_id: str, scenario: str, response_len: int) -> None:
    entry = {
        "id": str(uuid.uuid4()),
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "user_id": user_id,
        "scenario": scenario,
        "response_length": response_len,
        "disclaimer_appended": True,
        "compliance_version": "SEBI-IA-2013",
    }
    with open(AUDIT_LOG_PATH, "a") as f:
        f.write(json.dumps(entry) + "\n")


def validate_input_safety(user_input: str) -> tuple[bool, str]:
    """Reject prompt injection and off-topic requests."""
    injection_patterns = [
        r"ignore (previous|all) instructions",
        r"you are now",
        r"jailbreak",
        r"pretend (you are|to be)",
        r"disregard (your|all) (previous )?instructions",
    ]
    for pattern in injection_patterns:
        if re.search(pattern, user_input, re.IGNORECASE):
            return False, "I can only help with personal finance questions. Please ask about tax, investments, or financial planning."
    return True, ""
